// src/components/Entry.vue
<template>
  <div>
    <nuxt-link :to="path">
      <h4 class="has-text-weight-light has-text-black">{{ entry.createdAt | toISODateString }}</h4>
      <h1 class="has-text-weight-bold has-text-black is-size-4">{{ entry.title }}</h1>
      <p class="has-text-grey">{{ entry.description }}</p>
    </nuxt-link>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import { PostEntry } from '~/plugins/posts'
import { toISODateString } from '~/plugins/filters'

type Prop<T> = () => T

export default Vue.extend({
  props: {
    entry: Object as Prop<PostEntry>,
  },
  filters: {
    toISODateString,
  },
  computed: {
    path(): string {
      return `/posts/${this.entry.slug}`
    },
  },
})
</script>

// components/widgets/Entry.tsx
import * as React from 'react'
import Link from 'next/link'
import { PostEntry } from '../../lib/post'
import { toISODateString } from '../../lib/date'

const Entry: React.FC<{ entry: PostEntry }> = ({ entry }) => (
  <div>
    <Link as={`/posts/${entry.slug}`} href={`/post?slug=${entry.slug}`}>
      <a>
        <h4 className="has-text-weight-light has-text-black">{toISODateString(entry.createdAt)}</h4>
        <h1 className="has-text-weight-bold has-text-black is-size-4">{entry.title}</h1>
        <p className="has-text-grey">{entry.description}</p>
      </a>
    </Link>
  </div>
)

export default Entry
