// components/widgets/EntriesList.tsx
import * as React from 'react'
import Entry from './Entry'
import { PostEntry } from '../../lib/post'

const EntriesList: React.FC<{ entries: PostEntry[] }> = ({ entries }) => (
  <>
    {entries.map(entry => (
      <div key={entry.slug} className="border">
        <Entry entry={entry} />
      </div>
    ))}
    <style jsx>{`
      .border {
        border-bottom: solid 0.1rem grey;
      }
    `}</style>
  </>
)

export default EntriesList

// src/components/EntriesList.vue
<template>
  <div>
    <template v-for="entry in entries">
      <entry class="post-border" :key="entry.id" :entry="entry"/>
    </template>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import Entry from '~/components/Entry.vue'
export default Vue.extend({
  components: {
    Entry,
  },
  props: ['entries'],
})
</script>

<style scoped >
.post-border >>> {
  border-bottom: solid 0.1rem grey
}
</style>
