// src/pages/index.vue
<template>
  <section class="section">
    <entries-list :entries="entries"/>
  </section>
</template>

<script lang="ts">
import Vue from 'vue'
import EntriesList from '~/components/EntriesList.vue'
import { fetchEntries } from '~/plugins/posts'
import { toArray } from '~/plugins/util'

export default Vue.extend({
  async asyncData() {
    fetchEntries()[Symbol.asyncIterator]
    const entries = await toArray(fetchEntries())
    return {
      entries,
    }
  },
  components: {
    EntriesList,
  },
})
</script>

// pages/index.tsx
import * as React from 'react'
import Layout from '../components/layouts/default'
import EntriesList from '../components/widgets/EntriesList'
import { withInitialProps } from '../components/pages/withInitialProps'
import { PostEntry, fetchEntries } from '../lib/post'
import { toArray } from '../lib/async'

const Index: React.FC<{ entries: PostEntry[] }> = ({ entries }) => (
  <Layout>
    <section className="section">
      <EntriesList entries={entries} />
    </section>
  </Layout>
)

export default withInitialProps(async () => {
  const entries = await toArray(fetchEntries())
  return { entries }
})(Index)
