// src/layouts/default.vue
<template>
  <div>
    <app-header/>
    <main class="columns is-centered">
      <div class="column is-two-thirds">
        <nuxt/>
      </div>
    </main>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import AppHeader from '~/components/AppHeader.vue'

export default Vue.extend({
  components: {
    AppHeader,
  },
})
</script>

// components/layouts/default.tsx
// default layout
import * as React from 'react'
import '../../styles/styles.scss'
import Header from '../widgets/Header'

const Layout: React.FC = ({ children }) => {
  const title = process.env.title || 'Title'
  const description = process.env.description || 'Description'
  return (
    <div>
      <Header title={title} description={description} />
      <main className="columns is-centered">
        <div className="column is-two-thirds">{children}</div>
      </main>
    </div>
  )
}

export default Layout
